hello world started

diff --git a/11-install_commands_part2 b/11-install_commands_part2
--- a/11-install_commands_part2
+++ b/11-install_commands_part2
@@ -1,15 +1,18 @@
 #!/bin/bash
 
+
 USERID=$(id -u)
 
 if [ $USERID -ne 0 ]
 then
-    echo "ERROR: please run this is in root user"
+    echo e"ERROR: please run this is in root user" 
     exit 1 #give anything other then 0 upto 127
 else
     echo "you are running in root user"
 fi
 dnf list installed mysql -y
+#checks already installed or not if installed $? is 0, then (0 not equal is 0 = false) then
+# if not installed $? is not 0 . expression is true
 
 if [ $? -ne 0 ]
 then
